function RefModelFig(X1, Y1, YMatrix1, Y2)
%CREATEFIGURE(X1, Y1, YMatrix1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  YMATRIX1:  matrix of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 18-Mar-2019 11:08:34

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,3,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel('Temperature (K)');

% Create xlabel
xlabel('Time (Myr)');

% Create title
title('Interior Temperature','HorizontalAlignment','center','FontSize',20);

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot1,[0 2.0]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',14,'XGrid','on','YGrid','on');
% Create subplot
subplot2 = subplot(1,3,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot2,'LineWidth',3,'Color',[0 0 0]);
set(plot1(1),'DisplayName','z_c','LineStyle',':');
set(plot1(2),'DisplayName','b');

% Create ylabel
ylabel('Depth (km)');

% Create xlabel
xlabel('Time (Myr)');

% Create title
title('Ice Thickness','HorizontalAlignment','center','FontSize',20);

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,[0 1.5]);
box(subplot2,'on');
axis(subplot2,'ij');
% Set the remaining axes properties
set(subplot2,'FontSize',14,'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(subplot2,'show');
set(legend1,'Location','east');

% Create subplot
subplot3 = subplot(1,3,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X1,Y2,'Parent',subplot3,'LineWidth',3,'Color',[0 0 0]);

% Create ylabel
ylabel('Ra');

% Create xlabel
xlabel('Time (Myr)');

% Create title
title('Rayleigh Number','HorizontalAlignment','center','FontSize',20);

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot3,[0 1.5]);
box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'FontSize',14,'XGrid','on','YGrid','on');
